"""The comment check has to fail on its own tree, or it guards nothing."""

from __future__ import annotations

import importlib.util
import unittest
from pathlib import Path
from types import ModuleType

ROOT = Path(__file__).resolve().parent.parent
CHECK_COMMENTS_PATH = ROOT / "scripts" / "check_comments.py"


def _load_check_comments() -> ModuleType:
    spec = importlib.util.spec_from_file_location("dataforge_check_comments", CHECK_COMMENTS_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot load {CHECK_COMMENTS_PATH}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class CommentWidthTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.check = _load_check_comments()

    def _problems(self, source: str, *, typescript: bool = False) -> list[str]:
        reader = self.check._typescript_comments if typescript else self.check._python_comments
        return self.check._problems(ROOT / "sample.txt", reader(source))

    def test_the_limit_matches_the_formatter(self) -> None:
        self.assertEqual(self.check.MAX_LENGTH, 100)

    def test_a_comment_at_the_limit_passes(self) -> None:
        self.assertEqual(self._problems("# " + "a" * 98), [])

    def test_a_comment_over_the_limit_fails(self) -> None:
        self.assertEqual(len(self._problems("# " + "a" * 99)), 1)

    def test_a_long_url_is_exempt(self) -> None:
        self.assertEqual(self._problems("# https://example.com/" + "a" * 99), [])

    def test_a_hash_inside_a_string_is_not_a_comment(self) -> None:
        self.assertEqual(self._problems('value = "# ' + "a" * 99 + '"'), [])

    def test_a_trailing_comment_is_measured_without_its_code(self) -> None:
        self.assertEqual(self._problems("value = 1  # " + "a" * 95), [])

    def test_a_long_block_fails(self) -> None:
        over = "\n".join("# line" for _ in range(self.check.MAX_BLOCK_LINES + 1))
        self.assertEqual(len(self._problems(over)), 1)

    def test_a_block_at_the_limit_passes(self) -> None:
        allowed = "\n".join("# line" for _ in range(self.check.MAX_BLOCK_LINES))
        self.assertEqual(self._problems(allowed), [])

    def test_separated_blocks_are_counted_apart(self) -> None:
        pair = "# one\n# two\n\nvalue = 1\n\n# three\n# four"
        self.assertEqual(self._problems(pair), [])

    def test_a_long_typescript_comment_fails(self) -> None:
        self.assertEqual(len(self._problems("// " + "a" * 98, typescript=True)), 1)

    def test_a_jsdoc_continuation_counts_as_a_comment(self) -> None:
        self.assertEqual(len(self._problems(" * " + "a" * 99, typescript=True)), 1)

    def test_a_generated_file_is_skipped(self) -> None:
        self.assertTrue(self.check._is_generated("// Generated by scripts/generate_types.py"))
        self.assertFalse(self.check._is_generated("// Hand written"))

    def test_the_repository_is_clean(self) -> None:
        self.assertEqual(self.check.main(), 0)


if __name__ == "__main__":
    unittest.main()
