---
job: "extension"
config:
  name: ""
  process:
    - type: "diffusion_trainer"
      training_folder: ""
      device: "cuda"
      trigger_word: null
      performance_log_every: 10
      network:
        type: "lora"
        linear: 16
        linear_alpha: 16
        network_kwargs:
          ignore_if_contains:
            - "adaln_proj"
      save:
        dtype: "bf16"
        save_every: 500
        max_step_saves_to_keep: 4
        save_format: "diffusers"
      datasets:
        - folder_path: ""
          default_caption: ""
          caption_ext: "txt"
          caption_dropout_rate: 0.05
          cache_latents_to_disk: true
          shrink_video_to_frames: true
          num_frames: 39
          do_i2v: true
          resolution:
            - 224
      train:
        batch_size: 1
        steps: 1000
        gradient_accumulation: 1
        train_unet: true
        train_text_encoder: false
        gradient_checkpointing: true
        noise_scheduler: "flowmatch"
        optimizer: "automagic3"
        timestep_type: "shift"
        content_or_style: "balanced"
        optimizer_params:
          weight_decay: 0.0001
        lr: 0.0001
        cache_text_embeddings: true
        skip_first_sample: false
        dtype: "bf16"
        loss_type: "mse"
        do_differential_guidance: true
        differential_guidance_scale: 3
        do_guidance_loss: true
        guidance_loss_target: 3.5
      logging:
        log_every: 1
        use_ui_logger: true
      model:
        name_or_path: "Comfy-Org/MiniMax-H3"
        quantize: true
        qtype: "convrot8"
        quantize_te: true
        qtype_te: "nvfp4"
        arch: "minimax_h3"
        low_vram: true
        assistant_lora_path: "ostris/minimax_h3_training_adapter/minimax_h3_training_adapter_v1.safetensors"
      sample:
        sampler: "flowmatch"
        sample_every: 200
        sample_start_step: 0
        width: 512
        height: 512
        samples:
          - prompt: "example prompt"
        neg: ""
        seed: 42
        walk_seed: false
        guidance_scale: 1
        sample_steps: 20
        num_frames: 54
        fps: 24
meta:
  name: "[name]"
  version: "1.0"
