import type { LucideIcon } from "lucide-react";

export type AppIcon = LucideIcon;

export { iconAiToolkit, iconComfyUi } from "./brandIcons";

export {
  iconAdjustExposure,
  iconAdjustBrilliance,
  iconAdjustHighlights,
  iconAdjustShadows,
  iconAdjustContrast,
  iconAdjustBrightness,
  iconAdjustBlackPoint,
  iconAdjustSaturation,
  iconAdjustVibrance,
  iconAdjustWarmth,
  iconAdjustTint,
  iconAdjustHue,
  iconAdjustDefinition,
  iconAdjustNoiseReduction,
} from "./customIcons";

export {
  AlertTriangle as iconAlertTriangle,
  ArrowDown as iconArrowDown,
  ArrowDownWideNarrow as iconArrowDownWideNarrow,
  ArrowLeft as iconArrowLeft,
  ArrowLeftRight as iconArrowLeftRight,
  ArrowUp as iconArrowUp,
  ArrowUpRight as iconArrowUpRight,
  ArrowRight as iconArrowRight,
  Archive as iconArchive,
  ArchiveRestore as iconArchiveRestore,
  Ban as iconBan,
  Bell as iconBell,
  BellOff as iconBellOff,
  Bold as iconBold,
  BookOpen as iconBookOpen,
  Bot as iconBot,
  Brain as iconBrain,
  Camera as iconCamera,
  ChartColumn as iconChartBar,
  Check as iconCheck,
  ChevronDown as iconChevronDown,
  ChevronLeft as iconChevronLeft,
  ChevronRight as iconChevronRight,
  ChevronUp as iconChevronUp,
  CircleAlert as iconCircleAlert,
  CircleCheck as iconCircleCheck,
  CircleDashed as iconCircleDashed,
  CircleQuestionMark as iconCircleQuestionMark,
  Code as iconCode,
  Copy as iconCopy,
  Cpu as iconCpu,
  Crop as iconCrop,
  Dot as iconDot,
  Droplets as iconDroplets,
  Eraser as iconEraser,
  Expand as iconExpand,
  FileBraces as iconFileBraces,
  FileCheck as iconFileCheck,
  FileDown as iconFileDown,
  FileImage as iconFileImage,
  FilePen as iconFilePen,
  FilePlus as iconFilePlus,
  FileText as iconFileText,
  Files as iconFiles,
  Filter as iconFilter,
  FilterX as iconFilterX,
  FlipHorizontal2 as iconFlipHorizontal,
  FlipVertical2 as iconFlipVertical,
  Folder as iconFolder,
  FolderInput as iconFolderInput,
  FolderOpen as iconFolderOpen,
  FolderPlus as iconFolderPlus,
  FolderTree as iconFolderTree,
  Gauge as iconGauge,
  Gpu as iconGpu,
  Grid2x2 as iconGrid2x2,
  Grid3x3 as iconGrid3x3,
  Hammer as iconHammer,
  HardDrive as iconHardDrive,
  Heading1 as iconHeading1,
  Heading2 as iconHeading2,
  Heading3 as iconHeading3,
  History as iconHistory,
  House as iconHome,
  Hourglass as iconHourglass,
  Image as iconImage,
  ImageDown as iconImageDown,
  Images as iconImages,
  Layers as iconLayers,
  Info as iconInfo,
  Italic as iconItalic,
  Keyboard as iconKeyboard,
  Link as iconLink,
  List as iconList,
  ListChecks as iconListChecks,
  ListOrdered as iconListOrdered,
  Loader2 as iconLoader2,
  Maximize2 as iconMaximize2,
  MemoryStick as iconMemoryStick,
  MessageCircleCheck as iconMessageCheck,
  MessageCircleDashed as iconMessageDashed,
  MessageCirclePlus as iconMessagePlus,
  MessageCircleWarning as iconMessageWarning,
  MessageSquareText as iconMessageSquareText,
  Moon as iconMoon,
  Palette as iconPalette,
  Pause as iconPause,
  Pencil as iconPencil,
  PencilSparkles as iconPencilSparkles,
  Play as iconPlay,
  Plus as iconPlus,
  Plug as iconPlug,
  Proportions as iconProportions,
  Quote as iconQuote,
  Regex as iconRegex,
  RefreshCw as iconRefresh,
  RemoveFormatting as iconRemoveFormatting,
  Replace as iconReplace,
  RotateCcw as iconRotateCcw,
  RotateCw as iconRotateCw,
  Rows3 as iconRows3,
  RulerDimensionLine as iconRulerDimensionLine,
  ScanSquare as iconScanSquare,
  Scissors as iconScissors,
  Search as iconSearch,
  Settings as iconSettings,
  Shredder as iconShredder,
  SlidersHorizontal as iconSliders,
  Sparkles as iconSparkles,
  SpellCheck2 as iconSpellCheck2,
  SquarePen as iconSquarePen,
  SquareSplitHorizontal as iconSquareSplitHorizontal,
  Stamp as iconStamp,
  Star as iconStar,
  StarPlusIcon as iconStarPlusIcon,
  StepBack as iconStepBack,
  StepForward as iconStepForward,
  Strikethrough as iconStrikethrough,
  Sun as iconSun,
  Tag as iconTag,
  Trash2 as iconTrash2,
  TriangleAlert as iconTriangleAlert,
  Undo2 as iconUndo2,
  Unlink as iconUnlink,
  Video as iconVideo,
  Volume2 as iconVolume2,
  VolumeX as iconVolumeX,
  WandSparkles as iconWandSparkles,
  X as iconX,
  Zap as iconZap,
} from "lucide-react";
