"""Check that comments stay as narrow as the code around them.

Run from the project root:
  backend/.venv/Scripts/python scripts/check_comments.py [--scope SCOPE]

Neither formatter reflows a comment, so nothing else bounds one. A rationale that
outgrows these limits belongs in a test, not beside the code.
"""

from __future__ import annotations

import argparse
import io
import sys
import tokenize
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Ruff's line-length, so a comment may not run wider than the code it sits in.
MAX_LENGTH = 100
MAX_BLOCK_LINES = 4

PYTHON_ROOTS = ("backend", "scripts")
TYPESCRIPT_ROOT = Path("frontend") / "src"
SKIP_DIRS = {".venv", "__pycache__", "node_modules", "dist", "coverage", "data"}
TYPESCRIPT_SUFFIXES = {".ts", ".tsx"}


class Comment:
    def __init__(self, line: int, text: str, *, own_line: bool) -> None:
        self.line = line
        self.text = text
        self.own_line = own_line


def _is_generated(source: str) -> bool:
    return any("Generated by" in line for line in source.splitlines()[:5])


def _walk(directory: Path, suffixes: set[str]) -> list[Path]:
    found = []
    for path in directory.rglob("*"):
        if path.suffix not in suffixes or SKIP_DIRS.intersection(path.parts):
            continue
        found.append(path)
    return sorted(found)


def _python_comments(source: str) -> list[Comment]:
    comments = []
    for token in tokenize.generate_tokens(io.StringIO(source).readline):
        if token.type != tokenize.COMMENT:
            continue
        own_line = token.line.strip().startswith("#")
        text = token.line.strip() if own_line else token.string.strip()
        comments.append(Comment(token.start[0], text, own_line=own_line))
    return comments


def _typescript_comments(source: str) -> list[Comment]:
    comments = []
    for number, line in enumerate(source.splitlines(), start=1):
        text = line.strip()
        if text.startswith(("//", "/*", "{/*")) or (text.startswith("*") and text != "*/"):
            comments.append(Comment(number, text, own_line=True))
    return comments


def _problems(path: Path, comments: list[Comment]) -> list[str]:
    relative = path.relative_to(ROOT).as_posix()
    found = []

    for comment in comments:
        if len(comment.text) <= MAX_LENGTH or "http" in comment.text:
            continue
        found.append(
            f"{relative}:{comment.line}: comment is {len(comment.text)} characters, "
            f"over the {MAX_LENGTH} allowed"
        )

    block: list[int] = []
    for comment in [c for c in comments if c.own_line] + [Comment(-1, "", own_line=False)]:
        if block and comment.line == block[-1] + 1:
            block.append(comment.line)
            continue
        if len(block) > MAX_BLOCK_LINES:
            found.append(
                f"{relative}:{block[0]}: comment block runs {len(block)} lines, "
                f"over the {MAX_BLOCK_LINES} allowed"
            )
        block = [comment.line]

    return found


def _check(paths: list[Path], reader) -> list[str]:
    found = []
    for path in paths:
        source = path.read_text(encoding="utf-8")
        if _is_generated(source):
            continue
        found.extend(_problems(path, reader(source)))
    return found


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--scope", choices=("all", "backend", "frontend"), default="all")
    args = parser.parse_args()

    found = []
    if args.scope != "frontend":
        paths = [p for root in PYTHON_ROOTS for p in _walk(ROOT / root, {".py"})]
        found.extend(_check(paths, _python_comments))
    if args.scope != "backend":
        paths = _walk(ROOT / TYPESCRIPT_ROOT, TYPESCRIPT_SUFFIXES)
        found.extend(_check(paths, _typescript_comments))

    for problem in found:
        print(problem)
    if found:
        print(f"\nFound {len(found)} comment problems.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
