"""Check comment line widths in backend and frontend sources."""

from __future__ import annotations

import argparse
import io
import re
import sys
import tokenize
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Ruff's line-length, so a comment may not run wider than the code it sits in.
MAX_LENGTH = 100

PYTHON_ROOTS = ("backend", "scripts")
TYPESCRIPT_ROOT = Path("frontend") / "src"
SKIP_DIRS = {".venv", "__pycache__", "node_modules", "dist", "coverage", "data"}
TYPESCRIPT_SUFFIXES = {".ts", ".tsx"}

_BLOCK_COMMENT = re.compile(r"/\*[\s\S]*?\*/")
_TRAILING_LINE_COMMENT = re.compile(r"(?<!:)//(.*)$")


class Comment:
    def __init__(self, line: int, text: str) -> None:
        self.line = line
        self.text = text


def _is_generated(source: str) -> bool:
    return any("Generated by" in line for line in source.splitlines()[:5])


def _walk(directory: Path, suffixes: set[str]) -> list[Path]:
    found = []
    for path in directory.rglob("*"):
        if path.suffix not in suffixes or SKIP_DIRS.intersection(path.parts):
            continue
        found.append(path)
    return sorted(found)


def _python_comments(source: str) -> list[Comment]:
    comments = []
    for token in tokenize.generate_tokens(io.StringIO(source).readline):
        if token.type != tokenize.COMMENT:
            continue
        own_line = token.line.strip().startswith("#")
        text = token.line.strip() if own_line else token.string.strip()
        comments.append(Comment(token.start[0], text))
    return comments


def _block_content_line(raw: str) -> str | None:
    stripped = raw.strip()
    if stripped.startswith("/*"):
        stripped = stripped[2:].lstrip("*").strip()
        if stripped.endswith("*/"):
            stripped = stripped[:-2].strip()
    elif stripped.endswith("*/"):
        stripped = stripped[:-2].strip()
        if stripped.startswith("*"):
            stripped = stripped[1:].strip()
    elif stripped.startswith("*"):
        stripped = stripped[1:].strip()
    return stripped or None


def _typescript_comments(source: str) -> list[Comment]:
    comments: list[Comment] = []
    occupied: set[int] = set()

    for match in _BLOCK_COMMENT.finditer(source):
        start = source[: match.start()].count("\n") + 1
        lines = match.group(0).splitlines() or [match.group(0)]
        for offset, raw in enumerate(lines):
            line_no = start + offset
            occupied.add(line_no)
            stripped = raw.strip()
            if _block_content_line(raw) is None:
                continue
            comments.append(Comment(line_no, stripped))

    for number, line in enumerate(source.splitlines(), start=1):
        if number in occupied:
            continue
        stripped = line.strip()
        if stripped.startswith("//"):
            comments.append(Comment(number, stripped))
            continue
        trailing = _TRAILING_LINE_COMMENT.search(line)
        if trailing:
            comments.append(Comment(number, "//" + trailing.group(1)))

    comments.sort(key=lambda comment: comment.line)
    return comments


def _comment_body(text: str) -> str:
    body = text.strip()
    if body.startswith("{/*"):
        body = body[3:]
    elif body.startswith("/*"):
        body = body[2:]
    elif body.startswith("//"):
        body = body[2:]
    elif body.startswith("#"):
        body = body[1:]
    elif body.startswith("*"):
        body = body[1:]
    body = body.strip()
    if body.endswith("*/}"):
        body = body[:-3]
    elif body.endswith("*/"):
        body = body[:-2]
    return body.strip()


def _is_url_comment(text: str) -> bool:
    return _comment_body(text).startswith(("http://", "https://"))


def _problems(path: Path, comments: list[Comment]) -> list[str]:
    relative = path.relative_to(ROOT).as_posix()
    found = []

    for comment in comments:
        if len(comment.text) <= MAX_LENGTH or _is_url_comment(comment.text):
            continue
        found.append(
            f"{relative}:{comment.line}: comment is {len(comment.text)} characters, "
            f"over the {MAX_LENGTH} allowed"
        )

    return found


def _check(paths: list[Path], reader) -> list[str]:
    found = []
    for path in paths:
        source = path.read_text(encoding="utf-8")
        if _is_generated(source):
            continue
        found.extend(_problems(path, reader(source)))
    return found


def collect_problems(scope: str = "all") -> list[str]:
    found = []
    if scope != "frontend":
        paths = [p for root in PYTHON_ROOTS for p in _walk(ROOT / root, {".py"})]
        found.extend(_check(paths, _python_comments))
    if scope != "backend":
        paths = _walk(ROOT / TYPESCRIPT_ROOT, TYPESCRIPT_SUFFIXES)
        found.extend(_check(paths, _typescript_comments))
    return found


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--scope", choices=("all", "backend", "frontend"), default="all")
    args = parser.parse_args(argv)

    found = collect_problems(args.scope)
    for problem in found:
        print(problem)
    if found:
        print(f"\nFound {len(found)} comment problems.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
