"""Generate frontend/src/shared/{types,constants,wireGuards}.ts from schemas.py and constants.py."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

# Before any backend import: older interpreters die on PEP 695 with a bare SyntaxError.
from py_version import require_python

require_python()

ROOT = Path(__file__).resolve().parent.parent
BACKEND = ROOT / "backend"
SHARED = ROOT / "frontend" / "src" / "shared"
OUTPUT = SHARED / "types.ts"
CONSTANTS_OUTPUT = SHARED / "constants.ts"
GUARDS_OUTPUT = SHARED / "wireGuards.ts"

#: FastAPI validation shapes and multipart bodies named after the route.
SKIP_EXACT = frozenset({"HTTPValidationError", "ValidationError"})
SKIP_PREFIX = "Body_"

RENAMES = {
    "JobResponse": "Job",
    "SystemSpecsResponse": "SystemSpecs",
    "ExternalOstrisJobResponse": "ExternalOstrisJob",
}

#: Deliberate divergences from the published schema.
FIELD_TYPES = {
    # Backend keeps ``str``: narrowing would fail the whole list on one legacy row.
    ("JobResponse", "job_type"): "JobType",
    ("JobResponse", "status"): "JobStatus",
    ("MediaTransferRequest", "paths"): "readonly string[]",
}

PRINT_WIDTH = 100


def _banner(source: str, note: str) -> str:
    return (
        f"// Generated by scripts/generate_types.py from {source}. Do not edit.\n"
        "//\n"
        "// Run `backend/.venv/Scripts/python scripts/run_checks.py --fix` to regenerate.\n"
        f"// {note}"
    )


def _load_backend() -> tuple[dict[str, Any], Any, Any]:
    """Import the app, and merge in the wire models no route mentions."""
    sys.path.insert(0, str(BACKEND))
    from main import app  # noqa: PLC0415  (importable only once the path is set)
    from pydantic import TypeAdapter  # noqa: PLC0415

    import constants  # noqa: PLC0415
    import schemas  # noqa: PLC0415

    spec = app.openapi()
    components: dict[str, Any] = spec["components"]["schemas"]

    for model in schemas.EXTRA_WIRE_MODELS:
        rendered = TypeAdapter(model).json_schema(
            ref_template="#/components/schemas/{model}",
        )
        for name, definition in rendered.pop("$defs", {}).items():
            components.setdefault(name, definition)
        components.setdefault(model.__name__, rendered)

    return spec, schemas, constants


def _refs(node: Any) -> list[str]:
    """Every schema name reachable from ``node``, including through containers."""
    found: list[str] = []
    if isinstance(node, dict):
        ref = node.get("$ref")
        if isinstance(ref, str):
            found.append(ref.rsplit("/", 1)[-1])
        for value in node.values():
            found.extend(_refs(value))
    elif isinstance(node, list):
        for value in node:
            found.extend(_refs(value))
    return found


def _reachable(roots: list[Any], components: dict[str, Any]) -> set[str]:
    seen: set[str] = set()
    pending = [name for root in roots for name in _refs(root)]
    while pending:
        name = pending.pop()
        if name in seen or name not in components:
            continue
        seen.add(name)
        pending.extend(_refs(components[name]))
    return seen


def _classify(spec: dict[str, Any]) -> tuple[set[str], set[str]]:
    """Split the components into response-reachable and request-only.

    A schema reachable from both is treated as a response: that is the direction whose
    rule is stricter, and getting it wrong the other way would make an always-sent
    field optional. Schemas on no route at all (the SSE events) fall out as responses
    for the same reason.
    """
    components = spec["components"]["schemas"]
    response_roots: list[Any] = []
    request_roots: list[Any] = []

    for operations in spec.get("paths", {}).values():
        for operation in operations.values():
            if not isinstance(operation, dict):
                continue
            body = operation.get("requestBody")
            if body is not None:
                request_roots.append(body)
            response_roots.append(operation.get("responses", {}))

    responses = _reachable(response_roots, components)
    return responses, _reachable(request_roots, components) - responses


def _ts_name(name: str) -> str:
    return RENAMES.get(name, name)


def _literal(value: Any) -> str:
    return json.dumps(value)


def _is_null(schema: dict[str, Any]) -> bool:
    return schema.get("type") == "null"


def _ts_type(schema: dict[str, Any]) -> str:
    """Render one JSON-schema node as a TypeScript type expression."""
    ref = schema.get("$ref")
    if isinstance(ref, str):
        return _ts_name(ref.rsplit("/", 1)[-1])

    if "const" in schema:
        return _literal(schema["const"])

    enum = schema.get("enum")
    if enum is not None:
        return " | ".join(_literal(value) for value in enum)

    for key in ("anyOf", "oneOf"):
        members = schema.get(key)
        if members:
            rendered = [_ts_type(member) for member in members if not _is_null(member)]
            if any(_is_null(member) for member in members):
                rendered.append("null")
            return " | ".join(dict.fromkeys(rendered)) or "null"

    schema_type = schema.get("type")
    if schema_type == "array":
        items = schema.get("items")
        if not items:
            return "unknown[]"
        rendered = _ts_type(items)
        return f"({rendered})[]" if " | " in rendered else f"{rendered}[]"
    if schema_type == "object":
        extra = schema.get("additionalProperties")
        if isinstance(extra, dict):
            return f"Record<string, {_ts_type(extra)}>"
        return "Record<string, unknown>"

    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(schema_type, "unknown")


def _doc_comment(text: str | None, indent: str = "") -> list[str]:
    if not text:
        return []
    lines = [line.rstrip() for line in text.strip().splitlines()]
    if len(lines) == 1:
        return [f"{indent}/** {lines[0]} */"]
    body = [f"{indent} * {line}".rstrip() for line in lines]
    return [f"{indent}/**", *body, f"{indent} */"]


def _render_alias(name: str, schema: dict[str, Any]) -> str:
    rendered = _ts_type(schema)
    lines = _doc_comment(schema.get("description"))
    single = f"export type {_ts_name(name)} = {rendered};"
    if len(single) <= PRINT_WIDTH:
        lines.append(single)
    else:
        lines.append(f"export type {_ts_name(name)} =")
        lines.extend(f"  | {member}" for member in rendered.split(" | "))
        lines[-1] += ";"
    return "\n".join(lines)


def _is_optional(prop: str, definition: dict[str, Any], required: set[str], is_response: bool) -> bool:
    """Whether the emitted property carries a ``?``.

    A default means "omit it" on the way in, which is what the API already means. On the
    way out pydantic serializes every field, so only nullability can make one absent from
    a caller's point of view.
    """
    if prop in required:
        return False
    if not is_response:
        return True
    members = definition.get("anyOf") or definition.get("oneOf") or []
    return any(_is_null(member) for member in members)


def _render_interface(name: str, schema: dict[str, Any], *, is_response: bool) -> str:
    required = set(schema.get("required", ()))
    lines = _doc_comment(schema.get("description"))

    properties = schema.get("properties", {})
    if not properties:
        # ESLint rejects the empty `interface {}`; `Record<string, never>` means a fieldless model.
        lines.append(f"export type {_ts_name(name)} = Record<string, never>;")
        return "\n".join(lines)

    lines.append(f"export interface {_ts_name(name)} {{")

    for prop, definition in properties.items():
        optional = _is_optional(prop, definition, required, is_response)
        override = FIELD_TYPES.get((name, prop))
        rendered = override if override is not None else _ts_type(definition)

        lines.extend(_doc_comment(definition.get("description"), indent="  "))
        lines.append(f"  {prop}{'?' if optional else ''}: {rendered};")

    lines.append("}")
    return "\n".join(lines)


GUARD_PRELUDE = """function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}"""


def _guard_name(name: str) -> str:
    return f"is{_ts_name(name)}"


def _check(schema: dict[str, Any], expr: str, components: dict[str, Any], depth: int = 0) -> str:
    """A TypeScript expression that is true when ``expr`` matches ``schema``."""
    ref = schema.get("$ref")
    if isinstance(ref, str):
        target = ref.rsplit("/", 1)[-1]
        if "properties" in components.get(target, {}):
            return f"{_guard_name(target)}({expr})"
        return _check(components[target], expr, components, depth)

    if "const" in schema:
        return f"{expr} === {_literal(schema['const'])}"

    enum = schema.get("enum")
    if enum is not None:
        return "(" + " || ".join(f"{expr} === {_literal(value)}" for value in enum) + ")"

    for key in ("anyOf", "oneOf"):
        members = schema.get(key)
        if members:
            parts = [_check(member, expr, components, depth) for member in members]
            return "(" + " || ".join(parts) + ")"

    schema_type = schema.get("type")
    if schema_type == "null":
        return f"{expr} === null"
    if schema_type == "array":
        entry = "entry" if depth == 0 else f"entry{depth}"
        items = schema.get("items")
        if not items:
            return f"Array.isArray({expr})"
        inner = _check(items, entry, components, depth + 1)
        return f"(Array.isArray({expr}) && {expr}.every(({entry}) => {inner}))"
    if schema_type == "object":
        extra = schema.get("additionalProperties")
        if isinstance(extra, dict):
            entry = "entry" if depth == 0 else f"entry{depth}"
            inner = _check(extra, entry, components, depth + 1)
            return f"(isRecord({expr}) && Object.values({expr}).every(({entry}) => {inner}))"
        return f"isRecord({expr})"

    primitive = {"string": "string", "integer": "number", "number": "number", "boolean": "boolean"}
    if schema_type in primitive:
        return f'typeof {expr} === "{primitive[schema_type]}"'

    return "true"


def _render_guard(name: str, schema: dict[str, Any], components: dict[str, Any]) -> str:
    required = set(schema.get("required", ()))
    ts_name = _ts_name(name)
    lines = [f"export function {_guard_name(name)}(value: unknown): value is {ts_name} {{"]
    lines.append("  if (!isRecord(value)) return false;")

    for prop, definition in schema.get("properties", {}).items():
        optional = _is_optional(prop, definition, required, is_response=True)
        # Always parenthesised: `!typeof x === "y"` negates typeof first, so it never rejects.
        check = f"!({_check(definition, f'value.{prop}', components)})"
        guard = f"value.{prop} !== undefined && {check}" if optional else check
        lines.append(f"  if ({guard}) return false;")

    lines.append("  return true;")
    lines.append("}")
    return "\n".join(lines)


def _guard_targets(roots: list[str], components: dict[str, Any]) -> list[str]:
    """Every object schema a guard needs, the roots' own dependencies included."""
    pending = list(roots)
    seen: list[str] = []
    while pending:
        name = pending.pop(0)
        schema = components.get(name)
        if schema is None or name in seen:
            continue
        seen.append(name)
        pending.extend(_refs(schema))
    return [name for name in seen if "properties" in components[name]]


def render_guards(spec: dict[str, Any], schemas: Any) -> str:
    components: dict[str, Any] = spec["components"]["schemas"]
    roots = [model.__name__ for model in schemas.GUARDED_WIRE_MODELS]
    targets = _guard_targets(roots, components)

    unions: list[str] = []
    for root in roots:
        members = components[root].get("oneOf") or components[root].get("anyOf") or []
        if not members:
            continue
        parts = " || ".join(_check(member, "value", components) for member in members)
        unions.append(
            f"export function {_guard_name(root)}(value: unknown): value is {_ts_name(root)} {{\n"
            f"  return {parts};\n"
            "}"
        )

    guards = [
        _render_guard(name, components[name], components)
        for name in sorted(targets, key=_ts_name)
    ]

    imported = sorted({_ts_name(name) for name in [*targets, *roots]})
    sections = [
        _banner(
            "backend/schemas.py",
            "Guards for schemas.GUARDED_WIRE_MODELS: what arrives unvalidated, checked.",
        ),
        "// These check the wire schema, not the narrower types.ts view of it. Where the\n"
        "// frontend narrows a deliberately loose backend `str` (Job.job_type, Job.status),\n"
        "// the guard stays at `str`: rejecting a job type retired since a row was written\n"
        "// would drop the whole frame, which is worse than the narrowing being optimistic.",
        "import type {\n" + "".join(f"  {name},\n" for name in imported) + '} from "@/shared/types";',
        GUARD_PRELUDE,
        *guards,
        *unions,
    ]
    return "\n\n".join(sections) + "\n"


def _ts_value(value: Any) -> str:
    if isinstance(value, (list, tuple)):
        return "[" + ", ".join(_literal(entry) for entry in value) + "] as const"
    return _literal(value)


def render_constants(constants: Any) -> str:
    lines = [
        _banner(
            "backend/constants.py",
            "These drive UI affordances only: the server re-validates every drop.",
        )
    ]
    lines.extend(
        f"export const {name} = {_ts_value(value)};"
        for name, value in constants.SHARED_CONSTANTS.items()
    )
    return "\n\n".join(lines) + "\n"


def render(spec: dict[str, Any]) -> str:
    components: dict[str, Any] = spec["components"]["schemas"]
    responses, requests = _classify(spec)

    aliases: list[str] = []
    response_types: list[str] = []
    request_types: list[str] = []

    for name in sorted(components, key=_ts_name):
        if name in SKIP_EXACT or name.startswith(SKIP_PREFIX):
            continue
        schema = components[name]
        if "properties" not in schema:
            aliases.append(_render_alias(name, schema))
        elif name in requests:
            request_types.append(_render_interface(name, schema, is_response=False))
        else:
            response_types.append(_render_interface(name, schema, is_response=True))

    sections = [
        _banner(
            "backend/schemas.py",
            "Frontend-only shapes belong in the module that uses them, never here.",
        ),
        *aliases,
        *response_types,
        "/**\n * Request bodies.\n *\n"
        " * Optional wherever the backend declares a default, so omitting a field is the\n"
        " * same \"use the default\" the API already means. Field names stay snake_case:\n"
        " * these cross the wire verbatim.\n */",
        *request_types,
    ]
    return "\n\n".join(sections) + "\n"


def main() -> int:
    argparse.ArgumentParser(description=__doc__).parse_args()

    spec, schemas, constants = _load_backend()
    outputs = {
        OUTPUT: render(spec),
        CONSTANTS_OUTPUT: render_constants(constants),
        GUARDS_OUTPUT: render_guards(spec, schemas),
    }

    for path, generated in outputs.items():
        current = path.read_text(encoding="utf-8") if path.is_file() else ""
        if generated == current:
            continue
        path.write_text(generated, encoding="utf-8", newline="\n")
        print(f"Wrote {path.relative_to(ROOT)}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
