"""Generate ``frontend/src/shared/types.ts`` from the FastAPI schema.

Run from the project root:
  backend/.venv/Scripts/python scripts/generate_types.py

``backend/schemas.py`` is the single source of truth for the wire format. This reads
what FastAPI publishes from it and writes the TypeScript the frontend imports, so the
two cannot drift. The output is not checked in; ``scripts/run_checks.py`` runs this
first, before anything compiles, lints, or tests the frontend.

Response types come out as a strict superset of the wire: a field the server always
sends is required, unless it can be ``null``, in which case it is optional and nullable.
Requiring the never-null defaults (``issue_fixes``, ``stats``) is what keeps ``?? []``
noise out of the app; leaving the nullable ones optional is what lets a fixture omit
``width`` without lying about what arrives.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
BACKEND = ROOT / "backend"
OUTPUT = ROOT / "frontend" / "src" / "shared" / "types.ts"

#: FastAPI's own validation shapes, plus the multipart form bodies it names after the
#: route. ``/api/files/import`` sends a ``FormData``, which needs no TypeScript type.
SKIP_EXACT = frozenset({"HTTPValidationError", "ValidationError"})
SKIP_PREFIX = "Body_"

#: The frontend has always called these by shorter names, and they read better.
RENAMES = {
    "JobResponse": "Job",
    "SystemSpecsResponse": "SystemSpecs",
    "ExternalOstrisJobResponse": "ExternalOstrisJob",
}

#: Deliberate divergences from the published schema. Everything here needs a reason:
#: this table is the whole hand-maintained surface that survives codegen.
FIELD_TYPES = {
    # ``str`` on the backend because persisted job rows can hold types and statuses
    # retired since they were written, and narrowing there would fail the whole list
    # on one legacy row. The frontend narrows and falls back via ``isKnownJobType``.
    ("JobResponse", "job_type"): "JobType",
    ("JobResponse", "status"): "JobStatus",
    # Selections are frozen before they are sent.
    ("MediaTransferRequest", "paths"): "readonly string[]",
}

BANNER = """// Generated by scripts/generate_types.py from backend/schemas.py. Do not edit.
//
// Run `backend/.venv/Scripts/python scripts/run_checks.py --fix` to regenerate after
// changing a wire model. Frontend-only shapes belong in the module that uses them,
// never here.
"""

PRINT_WIDTH = 100


def _load_spec() -> dict[str, Any]:
    """Import the app and merge in the wire models no route mentions."""
    sys.path.insert(0, str(BACKEND))
    from main import app  # noqa: PLC0415  (importable only once the path is set)
    from pydantic import TypeAdapter  # noqa: PLC0415

    import schemas  # noqa: PLC0415

    spec = app.openapi()
    components: dict[str, Any] = spec["components"]["schemas"]

    for model in schemas.EXTRA_WIRE_MODELS:
        rendered = TypeAdapter(model).json_schema(
            ref_template="#/components/schemas/{model}",
        )
        for name, definition in rendered.pop("$defs", {}).items():
            components.setdefault(name, definition)
        components.setdefault(model.__name__, rendered)

    return spec


def _refs(node: Any) -> list[str]:
    """Every schema name reachable from ``node``, including through containers."""
    found: list[str] = []
    if isinstance(node, dict):
        ref = node.get("$ref")
        if isinstance(ref, str):
            found.append(ref.rsplit("/", 1)[-1])
        for value in node.values():
            found.extend(_refs(value))
    elif isinstance(node, list):
        for value in node:
            found.extend(_refs(value))
    return found


def _reachable(roots: list[Any], components: dict[str, Any]) -> set[str]:
    seen: set[str] = set()
    pending = [name for root in roots for name in _refs(root)]
    while pending:
        name = pending.pop()
        if name in seen or name not in components:
            continue
        seen.add(name)
        pending.extend(_refs(components[name]))
    return seen


def _classify(spec: dict[str, Any]) -> tuple[set[str], set[str]]:
    """Split the components into response-reachable and request-only.

    A schema reachable from both is treated as a response: that is the direction whose
    rule is stricter, and getting it wrong the other way would make an always-sent
    field optional. Schemas on no route at all (the SSE events) fall out as responses
    for the same reason.
    """
    components = spec["components"]["schemas"]
    response_roots: list[Any] = []
    request_roots: list[Any] = []

    for operations in spec.get("paths", {}).values():
        for operation in operations.values():
            if not isinstance(operation, dict):
                continue
            body = operation.get("requestBody")
            if body is not None:
                request_roots.append(body)
            response_roots.append(operation.get("responses", {}))

    responses = _reachable(response_roots, components)
    return responses, _reachable(request_roots, components) - responses


def _ts_name(name: str) -> str:
    return RENAMES.get(name, name)


def _literal(value: Any) -> str:
    return json.dumps(value)


def _is_null(schema: dict[str, Any]) -> bool:
    return schema.get("type") == "null"


def _ts_type(schema: dict[str, Any]) -> str:
    """Render one JSON-schema node as a TypeScript type expression."""
    ref = schema.get("$ref")
    if isinstance(ref, str):
        return _ts_name(ref.rsplit("/", 1)[-1])

    if "const" in schema:
        return _literal(schema["const"])

    enum = schema.get("enum")
    if enum is not None:
        return " | ".join(_literal(value) for value in enum)

    for key in ("anyOf", "oneOf"):
        members = schema.get(key)
        if members:
            rendered = [_ts_type(member) for member in members if not _is_null(member)]
            if any(_is_null(member) for member in members):
                rendered.append("null")
            return " | ".join(dict.fromkeys(rendered)) or "null"

    schema_type = schema.get("type")
    if schema_type == "array":
        items = schema.get("items")
        if not items:
            return "unknown[]"
        rendered = _ts_type(items)
        return f"({rendered})[]" if " | " in rendered else f"{rendered}[]"
    if schema_type == "object":
        extra = schema.get("additionalProperties")
        if isinstance(extra, dict):
            return f"Record<string, {_ts_type(extra)}>"
        return "Record<string, unknown>"

    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(schema_type, "unknown")


def _doc_comment(text: str | None, indent: str = "") -> list[str]:
    if not text:
        return []
    lines = [line.rstrip() for line in text.strip().splitlines()]
    if len(lines) == 1:
        return [f"{indent}/** {lines[0]} */"]
    body = [f"{indent} * {line}".rstrip() for line in lines]
    return [f"{indent}/**", *body, f"{indent} */"]


def _render_alias(name: str, schema: dict[str, Any]) -> str:
    rendered = _ts_type(schema)
    lines = _doc_comment(schema.get("description"))
    single = f"export type {_ts_name(name)} = {rendered};"
    if len(single) <= PRINT_WIDTH:
        lines.append(single)
    else:
        lines.append(f"export type {_ts_name(name)} =")
        lines.extend(f"  | {member}" for member in rendered.split(" | "))
        lines[-1] += ";"
    return "\n".join(lines)


def _render_interface(name: str, schema: dict[str, Any], *, is_response: bool) -> str:
    required = set(schema.get("required", ()))
    lines = _doc_comment(schema.get("description"))
    lines.append(f"export interface {_ts_name(name)} {{")

    for prop, definition in schema.get("properties", {}).items():
        members = definition.get("anyOf") or definition.get("oneOf") or []
        nullable = any(_is_null(member) for member in members)
        # A default means "omit it" on the way in, which is what the API already means.
        # On the way out pydantic serializes every field, so only nullability can make
        # one absent from a caller's point of view.
        optional = prop not in required and (not is_response or nullable)

        override = FIELD_TYPES.get((name, prop))
        rendered = override if override is not None else _ts_type(definition)

        lines.extend(_doc_comment(definition.get("description"), indent="  "))
        lines.append(f"  {prop}{'?' if optional else ''}: {rendered};")

    lines.append("}")
    return "\n".join(lines)


def render() -> str:
    spec = _load_spec()
    components: dict[str, Any] = spec["components"]["schemas"]
    responses, requests = _classify(spec)

    aliases: list[str] = []
    response_types: list[str] = []
    request_types: list[str] = []

    for name in sorted(components, key=_ts_name):
        if name in SKIP_EXACT or name.startswith(SKIP_PREFIX):
            continue
        schema = components[name]
        if "properties" not in schema:
            aliases.append(_render_alias(name, schema))
        elif name in requests:
            request_types.append(_render_interface(name, schema, is_response=False))
        else:
            response_types.append(_render_interface(name, schema, is_response=True))

    sections = [
        BANNER.rstrip(),
        *aliases,
        *response_types,
        "/**\n * Request bodies.\n *\n"
        " * Optional wherever the backend declares a default, so omitting a field is the\n"
        " * same \"use the default\" the API already means. Field names stay snake_case:\n"
        " * these cross the wire verbatim.\n */",
        *request_types,
    ]
    return "\n\n".join(sections) + "\n"


def main() -> int:
    argparse.ArgumentParser(description=__doc__).parse_args()

    generated = render()
    current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else ""
    if generated == current:
        return 0

    OUTPUT.write_text(generated, encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
